# Generated by Django 4.2.20 on 2025-03-13 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Miscellaneous", "Pending"),
                            ("Classics", "Classics"),
                            ("Thriller", "Thriller"),
                            ("Fantasy", "Fantasy"),
                            ("Adventure", "Adventure"),
                            ("Self_help", "Self_help"),
                            ("Horror", "Horror"),
                        ],
                        default="Miscellaneous",
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("isbn", models.IntegerField(max_length=15, unique=True)),
                ("availability_status", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="users.author",
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(related_name="books", to="books.genre"),
                ),
            ],
        ),
    ]
