# Generated by Django 4.2.20 on 2025-03-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book", name="isbn", field=models.IntegerField(unique=True),
        ),
    ]
